apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogcmFwdG9yLWhlbGxvCiAgc2NyYXBlX2ludGVydmFsOiAxNXMKICBzY3JhcGVfdGltZW91dDogMTBzCiAgbWV0cmljc19wYXRoOiAvbWV0cmljcwogIHNjaGVtZTogaHR0cAogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czoKICAgIC0gcmFwdG9yLWhlbGxvLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6ODg3Nwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
